# Generated by Django 3.2 on 2021-04-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='evaluations',
            field=models.ManyToManyField(related_name='evaluate_evaluatee', to='evaluatapp.Evaluation'),
        ),
    ]
