# Generated by Django 3.2 on 2021-04-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluatapp', '0002_user_evaluations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='evaluations',
        ),
        migrations.AddField(
            model_name='user',
            name='evaluations_given',
            field=models.ManyToManyField(blank=True, related_name='evaluate_evaluator', to='evaluatapp.Evaluation'),
        ),
        migrations.AddField(
            model_name='user',
            name='evaluations_received',
            field=models.ManyToManyField(blank=True, related_name='evaluate_evaluatee', to='evaluatapp.Evaluation'),
        ),
    ]
