# Generated by Django 3.2 on 2021-04-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluatapp', '0005_alter_evaluation_evaluator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='evaluations_received',
            new_name='evaluations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='evaluations_given',
        ),
    ]
